name: Publish Shared to NuGet

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      Project_Path: WaveformTimeline.Shared/WaveformTimeline.Shared.csproj
      NuGet_Source: https://api.nuget.org/v3/index.json

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore Dependencies
      run: dotnet restore ${{ env.Project_Path }}

    - name: Build Project
      run: dotnet build ${{ env.Project_Path }} --configuration Release --no-restore

    - name: Pack NuGet Package
      run: dotnet pack ${{ env.Project_Path }} --configuration Release --no-build --output nupkg

    - name: Publish to NuGet
      run: dotnet nuget push "nupkg/*.nupkg" --source ${{ env.NuGet_Source }} --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
